# Generated by Django 4.2.7 on 2023-12-01 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='taskCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 15, 10, 18, 217772)),
        ),
    ]
