# Generated by Django 4.2.7 on 2023-12-01 09:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todolist3', '0002_alter_todolist_taskcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='taskComp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='taskCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 15, 19, 7, 965217)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='taskid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
